name: Run tests
on:
  push:
    paths:
      - src/**
      - tests/**
      - jest.config.json
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm run test:all

      - name: Run package tests
        run: npm run build && npm run test:package
